// <auto-generated />
using System;
using Enframework_learning_2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Enframework_learning_2.Migrations
{
    [DbContext(typeof(DbcontextEfcoreold))]
    [Migration("20241203235717_update tables")]
    partial class updatetables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Enframework_learning_2.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Enframework_learning_2.Blogimage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Blogforignkey")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Blogforignkey")
                        .IsUnique()
                        .HasFilter("[Blogforignkey] IS NOT NULL");

                    b.ToTable("blogimage");
                });

            modelBuilder.Entity("Enframework_learning_2.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Blogid")
                        .HasColumnType("int");

                    b.Property<int?>("Blogimageid")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posturl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Blogid");

                    b.HasIndex("Blogimageid");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Enframework_learning_2.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("stocks");
                });

            modelBuilder.Entity("Enframework_learning_2.Blogimage", b =>
                {
                    b.HasOne("Enframework_learning_2.Blog", "blog")
                        .WithOne("Blogimage")
                        .HasForeignKey("Enframework_learning_2.Blogimage", "Blogforignkey");

                    b.Navigation("blog");
                });

            modelBuilder.Entity("Enframework_learning_2.Post", b =>
                {
                    b.HasOne("Enframework_learning_2.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("Blogid");

                    b.HasOne("Enframework_learning_2.Blogimage", "blogimage")
                        .WithMany("Posts")
                        .HasForeignKey("Blogimageid");

                    b.Navigation("Blog");

                    b.Navigation("blogimage");
                });

            modelBuilder.Entity("Enframework_learning_2.Blog", b =>
                {
                    b.Navigation("Blogimage");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Enframework_learning_2.Blogimage", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
